version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: Udodok_frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    # ports: 
    #   - "3000:3000"
    stdin_open: true

  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: Udodok_Main_Nginx
    ports: 
      - "80:80"

  backend:
    build: 
      dockerfile: Dockerfile
      context: ./backend
    container_name: Udodok_backend
    volumes:
      - ./backend:/app
    # ports: 
    #   - "8080:8080"
